### ISSUE TITLE
필드오류

### ISSUE THREAD

**Issue by dekomani** [biud436/MV-App-Builder#11]
You have been opted out of telemetry. To change this, run: cordova telemetry on.
Plugin "cordova-plugin-insomnia" already installed on android.
Adding cordova-plugin-insomnia to package.json
cordova-plugin-insomnia 플러그인이 추가되었습니다.
config.xml 파일을 수정하였습니다
키스토어 파일이 이미 생성되어있습니다.
게임 폴더 복사를 시작합니다 [robocopy 사용]

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows                              
-------------------------------------------------------------------------------

  Started : 2020년 10월 22일 목요일 오후 1:48:17
   Source : C:\Users\dekomani\Desktop\��Ƣ\==\www\
     Dest : C:\Users\dekomani\Documents\RPG Maker MV Cordova Builder\test\www\

    Files : *.*
	    
  Options : *.* /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /R:1 /W:1 

------------------------------------------------------------------------------

	                   2	C:\Users\dekomani\Desktop\��Ƣ\==\www\
	    Older     		    1663	index.html
100%  
	                   0	C:\Users\dekomani\Desktop\��Ƣ\==\www\audio\
	                   1	C:\Users\dekomani\Desktop\��Ƣ\==\www\audio\se\
	                  17	C:\Users\dekomani\Desktop\��Ƣ\==\www\data\
	                   2	C:\Users\dekomani\Desktop\��Ƣ\==\www\fonts\
	                   1	C:\Users\dekomani\Desktop\��Ƣ\==\www\icon\
	                   0	C:\Users\dekomani\Desktop\��Ƣ\==\www\img\
	                   2	C:\Users\dekomani\Desktop\��Ƣ\==\www\img\characters\
	                  20	C:\Users\dekomani\Desktop\��Ƣ\==\www\img\system\
	                   7	C:\Users\dekomani\Desktop\��Ƣ\==\www\img\tilesets\
	                   1	C:\Users\dekomani\Desktop\��Ƣ\==\www\img\titles1\
	                   8	C:\Users\dekomani\Desktop\��Ƣ\==\www\js\
	                   6	C:\Users\dekomani\Desktop\��Ƣ\==\www\js\libs\
	                  11	C:\Users\dekomani\Desktop\��Ƣ\==\www\js\plugins\

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :        14         0        14         0         0         0
   Files :        78         1        77         0         0         0
   Bytes :    4.91 m     1.6 k    4.91 m         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00

   Speed :             1663000 Bytes/sec.
   Speed :              95.157 MegaBytes/min.
   Ended : 2020년 10월 22일 목요일 오후 1:48:17

폴더를 www 폴더로 복사하였습니다.
index.html 파일을 수정하였습니다.
build.json 파일을 찾았습니다

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\dekomani\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: C:\Users\dekomani\AppData\Local\Android\Sdk
Reading build config file: C:\Users\dekomani\Documents\RPG Maker MV Cordova Builder\test\build.json
Reading the keystore from: C:\Users\dekomani\Documents\RPG Maker MV Cordova Builder\test\android.keystore
빌드 중에 오류가 발생하였습니다.

**Comment by biud436** [comment]
안녕하세요. 혹시 자바 버전하고 SDK 유무는 안나왔나요? 아무래도 키스토어 관련된 문제인 것 같긴 합니다.

**Comment by dekomani** [comment]
sdk 유무는 나왔는데 문제는 코르도바가 안드로이드 프로그램 생성을 못하는 것과 플로그인 추가를 실패한다는 것입니다.

**Comment by dekomani** [comment]
sdk 유무는 나왔는데 문제는 코르도바가 안드로이드 프로그램 생성을 못하는 것과 플 로그인 추가를 실패한다는 것입니다.
